# Generated by Django 4.1 on 2022-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Cart'), ('O', 'Ordered')], max_length=2, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
