# Generated by Django 4.1 on 2022-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
