# Generated by Django 4.1 on 2022-08-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('product', '0002_product_description_alter_product_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
    ]
