# Generated by Django 4.1 on 2022-08-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Pharmacy', 'Pharmacy'), ('Deliveryman', 'Deliveryman')], max_length=12)),
            ],
        ),
    ]
