# Generated by Django 4.0.6 on 2022-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_birthday_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
