# Generated by Django 4.0.6 on 2022-07-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Non-Binary')], max_length=2)),
                ('birthday', models.DateField(blank=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('mobile_no', models.CharField(max_length=14)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=10)),
                ('specialist', models.CharField(max_length=20)),
                ('verified', models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeOfDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=30)),
                ('degree_date', models.DateField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
