# Generated by Django 4.0.6 on 2022-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
