# Generated by Django 4.0.6 on 2022-07-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeofdoctor',
            name='degree_date',
            field=models.DateField(null=True),
        ),
    ]
