# Generated by Django 4.1 on 2022-08-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_degreeofdoctor_degree_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_starttime', models.TimeField(null=True)),
                ('sat_endtime', models.TimeField(null=True)),
                ('sun_starttime', models.TimeField(null=True)),
                ('sun_endtime', models.TimeField(null=True)),
                ('mon_starttime', models.TimeField(null=True)),
                ('mon_endtime', models.TimeField(null=True)),
                ('tues_starttime', models.TimeField(null=True)),
                ('tues_endtime', models.TimeField(null=True)),
                ('wed_starttime', models.TimeField(null=True)),
                ('wed_endtime', models.TimeField(null=True)),
                ('thrs_starttime', models.TimeField(null=True)),
                ('thrs_endtime', models.TimeField(null=True)),
                ('fri_starttime', models.TimeField(null=True)),
                ('fri_endtime', models.TimeField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
