# Generated by Django 4.1 on 2022-08-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_password'),
        ('doctor', '0004_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='max_capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.chamber')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
