# Generated by Django 4.1 on 2022-08-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_prescriptiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionType',
        ),
    ]
