# Generated by Django 4.1 on 2022-08-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_delete_prescriptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prescriptionFields',
            field=models.CharField(default='name#age#sex', max_length=250),
        ),
    ]
