# Generated by Django 4.1 on 2022-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_prescriptionfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='R', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='prescriptionFields',
            field=models.CharField(default='NAME#AGE#SEX', max_length=250),
        ),
    ]
