# Generated by Django 4.1 on 2022-08-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_appointment_state_alter_doctor_prescriptionfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('R', 'requested'), ('O', 'ongoing'), ('C', 'completed')], default='R', max_length=2),
        ),
    ]
