# Generated by Django 4.1 on 2022-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_appointment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Requested', max_length=10),
        ),
    ]
