# Generated by Django 4.1 on 2022-08-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveryman', '0001_initial'),
        ('pharmacy', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Got_deliveryman', 'Got_deliveryman'), ('Picked', 'Picked'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('deliveryman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryman.deliveryman')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
            ],
        ),
    ]
