# Generated by Django 4.1 on 2022-08-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryman.deliveryman'),
        ),
    ]
